/*
 * tb_instruction_handler.h
 *
 *  Created on: 21 Jul 2018
 *      Author: john
 */

#ifndef TAINT_ENGINES_INSTR_HANDLERS_TB_INSTRUCTION_HANDLER_H_
#define TAINT_ENGINES_INSTR_HANDLERS_TB_INSTRUCTION_HANDLER_H_

#include "../../taint_policies/tb_cc_prepost.h"
#include "instrumentation_bunny.h"
#include "spill.h"

typedef struct {

    bool is_cached;
    IB_INSTRUM_OPT options;
    ib_insert_hndle_data_t instr_handler_data;

} tb_instr_hndlr_t;

typedef void (*tb_ih_spill_func_t)();

tb_instr_hndlr_t tb_ih_set_inline_instr_hndlr(
        ib_insert_hndle_func_t instr_handler_func, void *user_data,
        IB_INSTRUM_OPT options, ib_spill_regs_func_t spill_reg_func,
        ib_restore_regs_func_t restore_reg_func, void *spill_data);

tb_instr_hndlr_t tb_ih_set_cache_instr_hndlr(
        ib_insert_hndle_func_t instr_handler_func, void *user_data,
        IB_INSTRUM_OPT options, ib_spill_regs_func_t spill_reg_func,
        ib_restore_regs_func_t restore_reg_func, void *spill_data);

bool tb_ih_apply_bit_tracking(void *tb_ctx_opaque);


enum TB_INSTRUM_ID_t{

    // OP_ADD:
    TB_INSTRUM_ID_ADD_DREG_1_SMEM_1,
    TB_INSTRUM_ID_ADD_DREG_2_SMEM_2,
    TB_INSTRUM_ID_ADD_DREG_4_SMEM_4,
    TB_INSTRUM_ID_ADD_DREG_8_SMEM_8,

    TB_INSTRUM_ID_ADD_DREG_1_SIMM_1,
    TB_INSTRUM_ID_ADD_DREG_2_SIMM_2,
    TB_INSTRUM_ID_ADD_DREG_4_SIMM_4,

    TB_INSTRUM_ID_ADD_DREG_1_SREG_1,
    TB_INSTRUM_ID_ADD_DREG_2_SREG_2,
    TB_INSTRUM_ID_ADD_DREG_4_SREG_4,
    TB_INSTRUM_ID_ADD_DREG_8_SREG_8,

    TB_INSTRUM_ID_ADD_DMEM_1_SREG_1,
    TB_INSTRUM_ID_ADD_DMEM_2_SREG_2,
    TB_INSTRUM_ID_ADD_DMEM_4_SREG_4,
    TB_INSTRUM_ID_ADD_DMEM_8_SREG_8,

    TB_INSTRUM_ID_ADD_DMEM_1_SIMM_1,
    TB_INSTRUM_ID_ADD_DMEM_2_SIMM_2,
    TB_INSTRUM_ID_ADD_DMEM_4_SIMM_4,

    TB_INSTRUM_ID_ADD_DREG_2_SIMM_1,
    TB_INSTRUM_ID_ADD_DREG_4_SIMM_1,
    TB_INSTRUM_ID_ADD_DREG_8_SIMM_1,

    TB_INSTRUM_ID_ADD_DMEM_2_SIMM_1,
    TB_INSTRUM_ID_ADD_DMEM_4_SIMM_1,
    TB_INSTRUM_ID_ADD_DMEM_8_SIMM_1,

    // OP_OR:
    TB_INSTRUM_ID_OR_DREG_1_SMEM_1,
    TB_INSTRUM_ID_OR_DREG_2_SMEM_2,
    TB_INSTRUM_ID_OR_DREG_4_SMEM_4,
    TB_INSTRUM_ID_OR_DREG_8_SMEM_8,

    TB_INSTRUM_ID_OR_DREG_1_SIMM_1,
    TB_INSTRUM_ID_OR_DREG_2_SIMM_2,
    TB_INSTRUM_ID_OR_DREG_4_SIMM_4,

    TB_INSTRUM_ID_OR_DREG_1_SREG_1,
    TB_INSTRUM_ID_OR_DREG_2_SREG_2,
    TB_INSTRUM_ID_OR_DREG_4_SREG_4,
    TB_INSTRUM_ID_OR_DREG_8_SREG_8,

    TB_INSTRUM_ID_OR_DMEM_1_SREG_1,
    TB_INSTRUM_ID_OR_DMEM_2_SREG_2,
    TB_INSTRUM_ID_OR_DMEM_4_SREG_4,
    TB_INSTRUM_ID_OR_DMEM_8_SREG_8,

    TB_INSTRUM_ID_OR_DMEM_1_SIMM_1,
    TB_INSTRUM_ID_OR_DMEM_2_SIMM_2,
    TB_INSTRUM_ID_OR_DMEM_4_SIMM_4,

    TB_INSTRUM_ID_OR_DREG_2_SIMM_1,
    TB_INSTRUM_ID_OR_DREG_4_SIMM_1,
    TB_INSTRUM_ID_OR_DREG_8_SIMM_1,

    TB_INSTRUM_ID_OR_DMEM_2_SIMM_1,
    TB_INSTRUM_ID_OR_DMEM_4_SIMM_1,
    TB_INSTRUM_ID_OR_DMEM_8_SIMM_1,

    // OP_ADC:
    TB_INSTRUM_ID_ADC_DREG_1_SMEM_1,
    TB_INSTRUM_ID_ADC_DREG_2_SMEM_2,
    TB_INSTRUM_ID_ADC_DREG_4_SMEM_4,
    TB_INSTRUM_ID_ADC_DREG_8_SMEM_8,

    TB_INSTRUM_ID_ADC_DREG_1_SIMM_1,
    TB_INSTRUM_ID_ADC_DREG_2_SIMM_2,
    TB_INSTRUM_ID_ADC_DREG_4_SIMM_4,

    TB_INSTRUM_ID_ADC_DREG_1_SREG_1,
    TB_INSTRUM_ID_ADC_DREG_2_SREG_2,
    TB_INSTRUM_ID_ADC_DREG_4_SREG_4,
    TB_INSTRUM_ID_ADC_DREG_8_SREG_8,

    TB_INSTRUM_ID_ADC_DMEM_1_SREG_1,
    TB_INSTRUM_ID_ADC_DMEM_2_SREG_2,
    TB_INSTRUM_ID_ADC_DMEM_4_SREG_4,
    TB_INSTRUM_ID_ADC_DMEM_8_SREG_8,

    TB_INSTRUM_ID_ADC_DMEM_1_SIMM_1,
    TB_INSTRUM_ID_ADC_DMEM_2_SIMM_2,
    TB_INSTRUM_ID_ADC_DMEM_4_SIMM_4,

    TB_INSTRUM_ID_ADC_DREG_2_SIMM_1,
    TB_INSTRUM_ID_ADC_DREG_4_SIMM_1,
    TB_INSTRUM_ID_ADC_DREG_8_SIMM_1,

    TB_INSTRUM_ID_ADC_DMEM_2_SIMM_1,
    TB_INSTRUM_ID_ADC_DMEM_4_SIMM_1,
    TB_INSTRUM_ID_ADC_DMEM_8_SIMM_1,

    // OP_SBB:
    TB_INSTRUM_ID_SBB_DREG_1_SMEM_1,
    TB_INSTRUM_ID_SBB_DREG_2_SMEM_2,
    TB_INSTRUM_ID_SBB_DREG_4_SMEM_4,
    TB_INSTRUM_ID_SBB_DREG_8_SMEM_8,

    TB_INSTRUM_ID_SBB_DREG_1_SIMM_1,
    TB_INSTRUM_ID_SBB_DREG_2_SIMM_2,
    TB_INSTRUM_ID_SBB_DREG_4_SIMM_4,

    TB_INSTRUM_ID_SBB_DREG_1_SREG_1,
    TB_INSTRUM_ID_SBB_DREG_2_SREG_2,
    TB_INSTRUM_ID_SBB_DREG_4_SREG_4,
    TB_INSTRUM_ID_SBB_DREG_8_SREG_8,

    TB_INSTRUM_ID_SBB_DMEM_1_SREG_1,
    TB_INSTRUM_ID_SBB_DMEM_2_SREG_2,
    TB_INSTRUM_ID_SBB_DMEM_4_SREG_4,
    TB_INSTRUM_ID_SBB_DMEM_8_SREG_8,

    TB_INSTRUM_ID_SBB_DMEM_1_SIMM_1,
    TB_INSTRUM_ID_SBB_DMEM_2_SIMM_2,
    TB_INSTRUM_ID_SBB_DMEM_4_SIMM_4,

    TB_INSTRUM_ID_SBB_DREG_2_SIMM_1,
    TB_INSTRUM_ID_SBB_DREG_4_SIMM_1,
    TB_INSTRUM_ID_SBB_DREG_8_SIMM_1,

    TB_INSTRUM_ID_SBB_DMEM_2_SIMM_1,
    TB_INSTRUM_ID_SBB_DMEM_4_SIMM_1,
    TB_INSTRUM_ID_SBB_DMEM_8_SIMM_1,

    // OP_AND:
    TB_INSTRUM_ID_AND_DREG_1_SMEM_1,
    TB_INSTRUM_ID_AND_DREG_2_SMEM_2,
    TB_INSTRUM_ID_AND_DREG_4_SMEM_4,
    TB_INSTRUM_ID_AND_DREG_8_SMEM_8,

    TB_INSTRUM_ID_AND_DREG_1_SIMM_1,
    TB_INSTRUM_ID_AND_DREG_2_SIMM_2,
    TB_INSTRUM_ID_AND_DREG_4_SIMM_4,

    TB_INSTRUM_ID_AND_DREG_1_SREG_1,
    TB_INSTRUM_ID_AND_DREG_2_SREG_2,
    TB_INSTRUM_ID_AND_DREG_4_SREG_4,
    TB_INSTRUM_ID_AND_DREG_8_SREG_8,

    TB_INSTRUM_ID_AND_DMEM_1_SREG_1,
    TB_INSTRUM_ID_AND_DMEM_2_SREG_2,
    TB_INSTRUM_ID_AND_DMEM_4_SREG_4,
    TB_INSTRUM_ID_AND_DMEM_8_SREG_8,

    TB_INSTRUM_ID_AND_DMEM_1_SIMM_1,
    TB_INSTRUM_ID_AND_DMEM_2_SIMM_2,
    TB_INSTRUM_ID_AND_DMEM_4_SIMM_4,

    TB_INSTRUM_ID_AND_DREG_2_SIMM_1,
    TB_INSTRUM_ID_AND_DREG_4_SIMM_1,
    TB_INSTRUM_ID_AND_DREG_8_SIMM_1,

    TB_INSTRUM_ID_AND_DMEM_2_SIMM_1,
    TB_INSTRUM_ID_AND_DMEM_4_SIMM_1,
    TB_INSTRUM_ID_AND_DMEM_8_SIMM_1,

    // OP_DAA:

    // OP_SUB:
    TB_INSTRUM_ID_SUB_DREG_1_SMEM_1,
    TB_INSTRUM_ID_SUB_DREG_2_SMEM_2,
    TB_INSTRUM_ID_SUB_DREG_4_SMEM_4,
    TB_INSTRUM_ID_SUB_DREG_8_SMEM_8,

    TB_INSTRUM_ID_SUB_DREG_1_SIMM_1,
    TB_INSTRUM_ID_SUB_DREG_2_SIMM_2,
    TB_INSTRUM_ID_SUB_DREG_4_SIMM_4,

    TB_INSTRUM_ID_SUB_DREG_1_SREG_1,
    TB_INSTRUM_ID_SUB_DREG_2_SREG_2,
    TB_INSTRUM_ID_SUB_DREG_4_SREG_4,
    TB_INSTRUM_ID_SUB_DREG_8_SREG_8,

    TB_INSTRUM_ID_SUB_DMEM_1_SREG_1,
    TB_INSTRUM_ID_SUB_DMEM_2_SREG_2,
    TB_INSTRUM_ID_SUB_DMEM_4_SREG_4,
    TB_INSTRUM_ID_SUB_DMEM_8_SREG_8,

    TB_INSTRUM_ID_SUB_DMEM_1_SIMM_1,
    TB_INSTRUM_ID_SUB_DMEM_2_SIMM_2,
    TB_INSTRUM_ID_SUB_DMEM_4_SIMM_4,

    TB_INSTRUM_ID_SUB_DREG_2_SIMM_1,
    TB_INSTRUM_ID_SUB_DREG_4_SIMM_1,
    TB_INSTRUM_ID_SUB_DREG_8_SIMM_1,

    TB_INSTRUM_ID_SUB_DMEM_2_SIMM_1,
    TB_INSTRUM_ID_SUB_DMEM_4_SIMM_1,
    TB_INSTRUM_ID_SUB_DMEM_8_SIMM_1,

    // OP_DAS:

    // OP_XOR:
    TB_INSTRUM_ID_XOR_DREG_1_SMEM_1,
    TB_INSTRUM_ID_XOR_DREG_2_SMEM_2,
    TB_INSTRUM_ID_XOR_DREG_4_SMEM_4,
    TB_INSTRUM_ID_XOR_DREG_8_SMEM_8,

    TB_INSTRUM_ID_XOR_DREG_1_SIMM_1,
    TB_INSTRUM_ID_XOR_DREG_2_SIMM_2,
    TB_INSTRUM_ID_XOR_DREG_4_SIMM_4,

    TB_INSTRUM_ID_XOR_DREG_1_SREG_1,
    TB_INSTRUM_ID_XOR_DREG_2_SREG_2,
    TB_INSTRUM_ID_XOR_DREG_4_SREG_4,
    TB_INSTRUM_ID_XOR_DREG_8_SREG_8,

    TB_INSTRUM_ID_XOR_DMEM_1_SREG_1,
    TB_INSTRUM_ID_XOR_DMEM_2_SREG_2,
    TB_INSTRUM_ID_XOR_DMEM_4_SREG_4,
    TB_INSTRUM_ID_XOR_DMEM_8_SREG_8,

    TB_INSTRUM_ID_XOR_DMEM_1_SIMM_1,
    TB_INSTRUM_ID_XOR_DMEM_2_SIMM_2,
    TB_INSTRUM_ID_XOR_DMEM_4_SIMM_4,

    TB_INSTRUM_ID_XOR_DREG_2_SIMM_1,
    TB_INSTRUM_ID_XOR_DREG_4_SIMM_1,
    TB_INSTRUM_ID_XOR_DREG_8_SIMM_1,

    TB_INSTRUM_ID_XOR_DMEM_2_SIMM_1,
    TB_INSTRUM_ID_XOR_DMEM_4_SIMM_1,
    TB_INSTRUM_ID_XOR_DMEM_8_SIMM_1,

    // OP_AAA:

    // OP_AAS:

    // OP_INC:
    TB_INSTRUM_ID_INC_DSMEM_1,
    TB_INSTRUM_ID_INC_DSMEM_2,
    TB_INSTRUM_ID_INC_DSMEM_4,
    TB_INSTRUM_ID_INC_DSMEM_8,
    TB_INSTRUM_ID_INC_DSREG_1,
    TB_INSTRUM_ID_INC_DSREG_2,
    TB_INSTRUM_ID_INC_DSREG_4,
    TB_INSTRUM_ID_INC_DSREG_8,

    // OP_DEC:
    TB_INSTRUM_ID_DEC_DSMEM_1,
    TB_INSTRUM_ID_DEC_DSMEM_2,
    TB_INSTRUM_ID_DEC_DSMEM_4,
    TB_INSTRUM_ID_DEC_DSMEM_8,
    TB_INSTRUM_ID_DEC_DSREG_1,
    TB_INSTRUM_ID_DEC_DSREG_2,
    TB_INSTRUM_ID_DEC_DSREG_4,
    TB_INSTRUM_ID_DEC_DSREG_8,

    // OP_PUSH:
    TB_INSTRUM_ID_PUSH_DMEM_1_SREG_1,
    TB_INSTRUM_ID_PUSH_DMEM_2_SREG_2,
    TB_INSTRUM_ID_PUSH_DMEM_4_SREG_4,
    TB_INSTRUM_ID_PUSH_DMEM_8_SREG_8,
    TB_INSTRUM_ID_PUSH_DMEM_1_SMEM_1,
    TB_INSTRUM_ID_PUSH_DMEM_2_SMEM_2,
    TB_INSTRUM_ID_PUSH_DMEM_4_SMEM_4,
    TB_INSTRUM_ID_PUSH_DMEM_8_SMEM_8,

    // OP_PUSH_IMM:

    // OP_POP:
    TB_INSTRUM_ID_POP_DREG_1_SMEM_1,
    TB_INSTRUM_ID_POP_DREG_2_SMEM_2,
    TB_INSTRUM_ID_POP_DREG_4_SMEM_4,
    TB_INSTRUM_ID_POP_DREG_8_SMEM_8,

    // OP_PUSHA:

    // OP_POPA:

    // OP_BOUND:

    // OP_ARPL:

    // OP_IMUL:
    TB_INSTRUM_ID_IMUL_DREG_2_SREG_1_SREG_1,
    TB_INSTRUM_ID_IMUL_DREG_2_SMEM_1_SREG_1,
    TB_INSTRUM_ID_IMUL_DREG_4_DREG_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_IMUL_DREG_4_DREG_4_SMEM_4_SREG_4,

    TB_INSTRUM_ID_IMUL_DREG_2_SMEM_2,
    TB_INSTRUM_ID_IMUL_DREG_4_SMEM_4,
    TB_INSTRUM_ID_IMUL_DREG_2_SREG_2,
    TB_INSTRUM_ID_IMUL_DREG_4_SREG_4,

    TB_INSTRUM_ID_IMUL_DREG_2_SIMM_1,
    TB_INSTRUM_ID_IMUL_DREG_4_SIMM_1,
    TB_INSTRUM_ID_IMUL_DREG_2_SIMM_2,
    TB_INSTRUM_ID_IMUL_DREG_4_SIMM_4,

    TB_INSTRUM_ID_IMUL_DREG_2_SREG_2_SIMM_2,
    TB_INSTRUM_ID_IMUL_DREG_4_SREG_4_SIMM_4,
    TB_INSTRUM_ID_IMUL_DREG_2_SMEM_2_SIMM_2,
    TB_INSTRUM_ID_IMUL_DREG_4_SMEM_4_SIMM_4,

    // OP_CALL:
    // OP_CALL_IND:
    // OP_CALL_FAR:
    // OP_CALL_FAR_IND:
    // OP_LOOPNE:
    // OP_LOOPE:
    // OP_LOOP:
    // OP_JECXZ:

    // OP_MOV_LD:
    TB_INSTRUM_ID_MOV_DREG_1_SMEM_1,
    TB_INSTRUM_ID_MOV_DREG_2_SMEM_2,
    TB_INSTRUM_ID_MOV_DREG_4_SMEM_4,
    TB_INSTRUM_ID_MOV_DREG_8_SMEM_8,

    // OP_MOV_ST:
    TB_INSTRUM_ID_MOV_DREG_1_SREG_1,
    TB_INSTRUM_ID_MOV_DREG_2_SREG_2,
    TB_INSTRUM_ID_MOV_DREG_4_SREG_4,
    TB_INSTRUM_ID_MOV_DREG_8_SREG_8,

    TB_INSTRUM_ID_MOV_DMEM_1_SREG_1,
    TB_INSTRUM_ID_MOV_DMEM_2_SREG_2,
    TB_INSTRUM_ID_MOV_DMEM_4_SREG_4,
    TB_INSTRUM_ID_MOV_DMEM_8_SREG_8,

    // OP_MOV_IMM:

    // OP_MOV_SEG:
    // OP_MOV_PRIV:

    // OP_LEA:
    TB_INSTRUM_ID_LEA_DREG_2_SREG_2_SREG_2,
    TB_INSTRUM_ID_LEA_DREG_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_LEA_DREG_8_SREG_8_SREG_8,

    TB_INSTRUM_ID_LEA_BASE_DREG_2_SREG_2,
    TB_INSTRUM_ID_LEA_BASE_DREG_4_SREG_4,
    TB_INSTRUM_ID_LEA_BASE_DREG_8_SREG_8,

    TB_INSTRUM_ID_LEA_INDEX_DREG_2_SREG_2,
    TB_INSTRUM_ID_LEA_INDEX_DREG_4_SREG_4,
    TB_INSTRUM_ID_LEA_INDEX_DREG_8_SREG_8,

    // OP_XCHG:
    TB_INSTRUM_ID_XCHG_REG_1_REG_1,
    TB_INSTRUM_ID_XCHG_REG_2_REG_2,
    TB_INSTRUM_ID_XCHG_REG_4_REG_4,
    TB_INSTRUM_ID_XCHG_REG_8_REG_8,
    TB_INSTRUM_ID_XCHG_MEM_1_REG_1,
    TB_INSTRUM_ID_XCHG_MEM_2_REG_2,
    TB_INSTRUM_ID_XCHG_MEM_4_REG_4,
    TB_INSTRUM_ID_XCHG_MEM_8_REG_8,
    TB_INSTRUM_ID_XCHG_REG_1_MEM_1,
    TB_INSTRUM_ID_XCHG_REG_2_MEM_2,
    TB_INSTRUM_ID_XCHG_REG_4_MEM_4,
    TB_INSTRUM_ID_XCHG_REG_8_MEM_8,

    // OP_CWDE:
    // OP_CDQ:
    // OP_FWAIT:
    // OP_PUSHF:
    // OP_POPF:
    // OP_SAHF:
    // OP_LAHF:

    // OP_RET:

    // OP_RET_FAR:

    // OP_LES:

    // OP_LDS:

    // OP_ENTER:

    // OP_LEAVE:
    TB_INSTRUM_ID_LEAVE_DREG_4_DREG_4_SREG_4_SMEM_4,
    TB_INSTRUM_ID_LEAVE_DREG_8_DREG_8_SREG_8_SMEM_8,

    // OP_INTO:

    // OP_IRET:
    // OP_AAM:

    // OP_AAD:

    // OP_XLAT:
    // OP_IN:
    // OP_OUT:
    // OP_HLT:

    // OP_LAR:
    // OP_LSL:

    // OP_CLTS:
    // OP_SYSRET:
    // OP_INVD:
    // OP_WBINVD:
    // OP_UD2A:
    // OP_NOP_MODRM:
    // OP_MOVNTPS:

    // OP_MOVNTPD:

    // OP_WRMSR:
    // OP_RDTSC:
    // OP_RDMSR:
    // OP_RDPMC:

    // OP_CMOVO:
    TB_INSTRUM_ID_CMOVO_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVO_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVO_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVO_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVO_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVO_DREG_8_SMEM_8,

    // OP_CMOVNO:
    TB_INSTRUM_ID_CMOVNO_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVNO_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVNO_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVNO_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVNO_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVNO_DREG_8_SMEM_8,

    // OP_CMOVB:
    TB_INSTRUM_ID_CMOVB_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVB_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVB_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVB_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVB_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVB_DREG_8_SMEM_8,

    // OP_CMOVNB:
    TB_INSTRUM_ID_CMOVNB_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVNB_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVNB_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVNB_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVNB_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVNB_DREG_8_SMEM_8,

    // OP_CMOVZ:
    TB_INSTRUM_ID_CMOVE_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVE_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVE_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVE_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVE_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVE_DREG_8_SMEM_8,

    // OP_CMOVNZ:
    TB_INSTRUM_ID_CMOVNE_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVNE_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVNE_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVNE_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVNE_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVNE_DREG_8_SMEM_8,

    // OP_CMOVBE:
    TB_INSTRUM_ID_CMOVBE_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVBE_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVBE_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVBE_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVBE_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVBE_DREG_8_SMEM_8,

    // OP_CMOVNBE:
    TB_INSTRUM_ID_CMOVNBE_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVNBE_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVNBE_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVNBE_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVNBE_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVNBE_DREG_8_SMEM_8,

    // OP_CMOVS:
    TB_INSTRUM_ID_CMOVS_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVS_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVS_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVS_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVS_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVS_DREG_8_SMEM_8,

    // OP_CMOVNS:
    TB_INSTRUM_ID_CMOVNS_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVNS_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVNS_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVNS_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVNS_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVNS_DREG_8_SMEM_8,

    // OP_CMOVP:
    TB_INSTRUM_ID_CMOVP_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVP_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVP_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVP_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVP_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVP_DREG_8_SMEM_8,

    // OP_CMOVNP:
    TB_INSTRUM_ID_CMOVNP_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVNP_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVNP_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVNP_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVNP_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVNP_DREG_8_SMEM_8,

    // OP_CMOVL:
    TB_INSTRUM_ID_CMOVL_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVL_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVL_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVL_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVL_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVL_DREG_8_SMEM_8,

    // OP_CMOVNL:
    TB_INSTRUM_ID_CMOVGE_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVGE_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVGE_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVGE_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVGE_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVGE_DREG_8_SMEM_8,

    // OP_CMOVLE:
    TB_INSTRUM_ID_CMOVLE_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVLE_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVLE_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVLE_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVLE_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVLE_DREG_8_SMEM_8,

    // OP_CMOVNLE:
    TB_INSTRUM_ID_CMOVG_DREG_2_SREG_2,
    TB_INSTRUM_ID_CMOVG_DREG_4_SREG_4,
    TB_INSTRUM_ID_CMOVG_DREG_8_SREG_8,
    TB_INSTRUM_ID_CMOVG_DREG_2_SMEM_2,
    TB_INSTRUM_ID_CMOVG_DREG_4_SMEM_4,
    TB_INSTRUM_ID_CMOVG_DREG_8_SMEM_8,

    // OP_PUNPCKLBW:
    TB_INSTRUM_ID_PUNPCKLBW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PUNPCKLBW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PUNPCKLBW_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKLBW_DREG_16_SMEM_16,

    // OP_PUNPCKLWD:
    TB_INSTRUM_ID_PUNPCKLWD_DREG_8_SREG_8,
    TB_INSTRUM_ID_PUNPCKLWD_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PUNPCKLWD_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKLWD_DREG_16_SMEM_16,

    // OP_PUNPCKLDQ:
    TB_INSTRUM_ID_PUNPCKLDQ_DREG_8_SREG_8,
    TB_INSTRUM_ID_PUNPCKLDQ_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PUNPCKLDQ_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKLDQ_DREG_16_SMEM_16,

    // OP_PACKSSWB:
    TB_INSTRUM_ID_PACKSSWB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PACKSSWB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PACKSSWB_DREG_16_SREG_16,
    TB_INSTRUM_ID_PACKSSWB_DREG_16_SMEM_16,

    // OP_PCMPGTB:
    TB_INSTRUM_ID_PCMPGTB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPGTB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPGTB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPGTB_DREG_16_SREG_16,

    // OP_PCMPGTW:
    TB_INSTRUM_ID_PCMPGTW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPGTW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPGTW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPGTW_DREG_16_SREG_16,

    // OP_PCMPGTD:
    TB_INSTRUM_ID_PCMPGTD_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPGTD_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPGTD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPGTD_DREG_16_SREG_16,

    // OP_PACKUSWB:
    TB_INSTRUM_ID_PACKUSWB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PACKUSWB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PACKUSWB_DREG_16_SREG_16,
    TB_INSTRUM_ID_PACKUSWB_DREG_16_SMEM_16,

    // OP_PUNPCKHBW:
    TB_INSTRUM_ID_PUNPCKHBW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PUNPCKHBW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PUNPCKHBW_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKHBW_DREG_16_SMEM_16,

    // OP_PUNPCKHWD:
    TB_INSTRUM_ID_PUNPCKHWD_DREG_8_SREG_8,
    TB_INSTRUM_ID_PUNPCKHWD_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PUNPCKHWD_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKHWD_DREG_16_SMEM_16,

    // OP_PUNPCKHDQ:
    TB_INSTRUM_ID_PUNPCKHDQ_DREG_8_SREG_8,
    TB_INSTRUM_ID_PUNPCKHDQ_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PUNPCKHDQ_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKHDQ_DREG_16_SMEM_16,

    // OP_PACKSSDW:
    TB_INSTRUM_ID_PACKSSDW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PACKSSDW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PACKSSDW_DREG_16_SREG_16,
    TB_INSTRUM_ID_PACKSSDW_DREG_16_SMEM_16,

    // OP_PUNPCKLQDQ:
    TB_INSTRUM_ID_PUNPCKLQDQ_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKLQDQ_DREG_16_SMEM_16,

    // OP_PUNPCKHQDQ:
    TB_INSTRUM_ID_PUNPCKHQDQ_DREG_16_SREG_16,
    TB_INSTRUM_ID_PUNPCKHQDQ_DREG_16_SMEM_16,

    // OP_MOVD:
    TB_INSTRUM_ID_MOVD_DREG_4_SMEM_4,
    TB_INSTRUM_ID_MOVD_DREG_4_SREG_4,
    TB_INSTRUM_ID_MOVD_DMEM_4_SREG_4,

    TB_INSTRUM_ID_MOVD_DREG_8_SMEM_4,
    TB_INSTRUM_ID_MOVD_DREG_8_SREG_4,
    TB_INSTRUM_ID_MOVD_DREG_4_SREG_8,
    TB_INSTRUM_ID_MOVD_DMEM_4_SREG_8,

    TB_INSTRUM_ID_MOVD_DREG_16_SMEM_4,
    TB_INSTRUM_ID_MOVD_DREG_16_SREG_4,
    TB_INSTRUM_ID_MOVD_DMEM_4_SREG_16,
    TB_INSTRUM_ID_MOVD_DREG_4_SREG_16,

    // OP_MOVQ:
    TB_INSTRUM_ID_MOVQ_DREG_8_SMEM_8,
    TB_INSTRUM_ID_MOVQ_DREG_8_SREG_8,
    TB_INSTRUM_ID_MOVQ_DMEM_8_SREG_8,

    TB_INSTRUM_ID_MOVQ_DREG_16_SMEM_8,
    TB_INSTRUM_ID_MOVQ_DREG_16_SREG_8,
    TB_INSTRUM_ID_MOVQ_DMEM_8_SREG_16,
    TB_INSTRUM_ID_MOVQ_DREG_8_SREG_16,

    // OP_MOVDQU:
    TB_INSTRUM_ID_MOVDQU_DREG_16_SMEM_16,
    TB_INSTRUM_ID_MOVDQU_DMEM_16_SREG_16,
    TB_INSTRUM_ID_MOVDQU_DREG_16_SREG_16,

    // OP_MOVDQA:
    TB_INSTRUM_ID_MOVDQA_DREG_16_SMEM_16,
    TB_INSTRUM_ID_MOVDQA_DMEM_16_SREG_16,
    TB_INSTRUM_ID_MOVDQA_DREG_16_SREG_16,

    // OP_PSHUFW:
    TB_INSTRUM_ID_PSHUFW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PSHUFW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PSHUFW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PSHUFW_DREG_16_SREG_16,

    // OP_PSHUFD:
    TB_INSTRUM_ID_PSHUFD_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PSHUFD_DREG_8_SREG_8,
    TB_INSTRUM_ID_PSHUFD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PSHUFD_DREG_16_SREG_16,

    // OP_PSHUFHW:
    TB_INSTRUM_ID_PSHUFHW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PSHUFHW_DREG_16_SREG_16,

    // OP_PSHUFLW:
    TB_INSTRUM_ID_PSHUFLW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PSHUFLW_DREG_16_SREG_16,

    // OP_PCMPEQB:
    TB_INSTRUM_ID_PCMPEQB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPEQB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPEQB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPEQB_DREG_16_SREG_16,

    // OP_PCMPEQW:
    TB_INSTRUM_ID_PCMPEQW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPEQW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPEQW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPEQW_DREG_16_SREG_16,

    // OP_PCMPEQD:
    TB_INSTRUM_ID_PCMPEQD_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPEQD_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPEQD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPEQD_DREG_16_SREG_16,

    // OP_EMMS:

    // OP_SETO:

    // OP_SETNO:

    // OP_SETB:

    // OP_SETNB:

    // OP_SETZ:

    // OP_SETNZ:

    // OP_SETBE:

    // OP_SETNBE:

    // OP_SETS:

    // OP_SETNS:

    // OP_SETP:

    // OP_SETNP:

    // OP_SETL:

    // OP_SETNL:

    // OP_SETLE:

    // OP_SETNLE:

    // OP_CPUID:

    // OP_SHLD:
    TB_INSTRUM_ID_SHLD_DMEM_2_SREG_2_SIMM_1,
    TB_INSTRUM_ID_SHLD_DMEM_4_SREG_4_SIMM_1,
    TB_INSTRUM_ID_SHLD_DMEM_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_SHLD_DREG_2_SREG_2_SIMM_1,
    TB_INSTRUM_ID_SHLD_DREG_4_SREG_4_SIMM_1,
    TB_INSTRUM_ID_SHLD_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_SHLD_DMEM_2_SREG_2_SREG_1,
    TB_INSTRUM_ID_SHLD_DMEM_4_SREG_4_SREG_1,
    TB_INSTRUM_ID_SHLD_DMEM_8_SREG_8_SREG_1,
    TB_INSTRUM_ID_SHLD_DREG_2_SREG_2_SREG_1,
    TB_INSTRUM_ID_SHLD_DREG_4_SREG_4_SREG_1,
    TB_INSTRUM_ID_SHLD_DREG_8_SREG_8_SREG_1,

    // OP_RSM:
    // OP_BTS:

    // OP_SHRD:
    TB_INSTRUM_ID_SHRD_DMEM_2_SREG_2_SIMM_1,
    TB_INSTRUM_ID_SHRD_DMEM_4_SREG_4_SIMM_1,
    TB_INSTRUM_ID_SHRD_DMEM_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_SHRD_DREG_2_SREG_2_SIMM_1,
    TB_INSTRUM_ID_SHRD_DREG_4_SREG_4_SIMM_1,
    TB_INSTRUM_ID_SHRD_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_SHRD_DMEM_2_SREG_2_SREG_1,
    TB_INSTRUM_ID_SHRD_DMEM_4_SREG_4_SREG_1,
    TB_INSTRUM_ID_SHRD_DMEM_8_SREG_8_SREG_1,
    TB_INSTRUM_ID_SHRD_DREG_2_SREG_2_SREG_1,
    TB_INSTRUM_ID_SHRD_DREG_4_SREG_4_SREG_1,
    TB_INSTRUM_ID_SHRD_DREG_8_SREG_8_SREG_1,

    // OP_CMPXCHG:
    TB_INSTRUM_ID_CMPXCHG_SREG_1_SMEM_1,
    TB_INSTRUM_ID_CMPXCHG_SREG_2_SMEM_2,
    TB_INSTRUM_ID_CMPXCHG_SREG_4_SMEM_4,
    TB_INSTRUM_ID_CMPXCHG_SREG_8_SMEM_8,

    TB_INSTRUM_ID_CMPXCHG_SREG_1_SREG_1,
    TB_INSTRUM_ID_CMPXCHG_SREG_2_SREG_2,
    TB_INSTRUM_ID_CMPXCHG_SREG_4_SREG_4,
    TB_INSTRUM_ID_CMPXCHG_SREG_8_SREG_8,

    // OP_LSS:
    // OP_BTR:
    // OP_LFS:
    // OP_LGS:

    // OP_MOVZX:
	TB_INSTRUM_ID_MOVZX_DREG_2_SMEM_1,
	TB_INSTRUM_ID_MOVZX_DREG_4_SMEM_1,
    TB_INSTRUM_ID_MOVZX_DREG_4_SMEM_2,
	TB_INSTRUM_ID_MOVZX_DREG_2_SREG_1,
	TB_INSTRUM_ID_MOVZX_DREG_4_SREG_1,
    TB_INSTRUM_ID_MOVZX_DREG_4_SREG_2,

    // OP_UD2B:
    // OP_BTC:
    // OP_BSF:
    TB_INSTRUM_ID_BSF_DREG_2_SMEM_2,
    TB_INSTRUM_ID_BSF_DREG_4_SMEM_4,
    TB_INSTRUM_ID_BSF_DREG_8_SMEM_8,
    TB_INSTRUM_ID_BSF_DREG_2_SREG_2,
    TB_INSTRUM_ID_BSF_DREG_4_SREG_4,
    TB_INSTRUM_ID_BSF_DREG_8_SREG_8,

    // OP_BSR:
    TB_INSTRUM_ID_BSR_DREG_2_SMEM_2,
    TB_INSTRUM_ID_BSR_DREG_4_SMEM_4,
    TB_INSTRUM_ID_BSR_DREG_8_SMEM_8,
    TB_INSTRUM_ID_BSR_DREG_2_SREG_2,
    TB_INSTRUM_ID_BSR_DREG_4_SREG_4,
    TB_INSTRUM_ID_BSR_DREG_8_SREG_8,

    // OP_MOVSX:
	TB_INSTRUM_ID_MOVSX_DREG_2_SMEM_1,
    TB_INSTRUM_ID_MOVSX_DREG_4_SMEM_1,
    TB_INSTRUM_ID_MOVSX_DREG_4_SMEM_2,
	TB_INSTRUM_ID_MOVSX_DREG_2_SREG_1,
    TB_INSTRUM_ID_MOVSX_DREG_4_SREG_1,
    TB_INSTRUM_ID_MOVSX_DREG_4_SREG_2,

    // OP_XADD:
    TB_INSTRUM_ID_XADD_REG_1_REG_1,
    TB_INSTRUM_ID_XADD_REG_2_REG_2,
    TB_INSTRUM_ID_XADD_REG_4_REG_4,
    TB_INSTRUM_ID_XADD_REG_8_REG_8,
    TB_INSTRUM_ID_XADD_MEM_1_REG_1,
    TB_INSTRUM_ID_XADD_MEM_2_REG_2,
    TB_INSTRUM_ID_XADD_MEM_4_REG_4,
    TB_INSTRUM_ID_XADD_MEM_8_REG_8,

    // OP_MOVNTI:

    // OP_PINSRW:

    // OP_PEXTRW:
    TB_INSTRUM_ID_PEXTRW_DREG_4_SREG_16,
    TB_INSTRUM_ID_PEXTRW_DREG_4_SREG_8,
    TB_INSTRUM_ID_PEXTRW_DMEM_2_SREG_16,

    // OP_BSWAP:
    TB_INSTRUM_ID_BSWAP_DSREG_4,
    TB_INSTRUM_ID_BSWAP_DSREG_8,
    TB_INSTRUM_ID_BSWAP_DSMEM_4,
    TB_INSTRUM_ID_BSWAP_DSMEM_8,

    // OP_PSRLW:
    TB_INSTRUM_ID_PSRLW_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSRLW_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSRLW_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSRLW_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSRLW_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSRLW_DREG_16_SREG_16_SIMM_1,

    // OP_PSRLD:
    TB_INSTRUM_ID_PSRLD_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSRLD_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSRLD_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSRLD_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSRLD_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSRLD_DREG_16_SREG_16_SIMM_1,

    // OP_PSRLQ:
    TB_INSTRUM_ID_PSRLQ_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSRLQ_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSRLQ_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSRLQ_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSRLQ_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSRLQ_DREG_16_SREG_16_SIMM_1,

    // OP_PADDQ:
    TB_INSTRUM_ID_PADDQ_DREG_8_SREG_8,
    TB_INSTRUM_ID_PADDQ_DREG_16_SREG_16,
    TB_INSTRUM_ID_PADDQ_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PADDQ_DREG_16_SMEM_16,

    // OP_PMULLW:
    TB_INSTRUM_ID_PMULLW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMULLW_DREG_16_SREG_16,
    TB_INSTRUM_ID_PMULLW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PMULLW_DREG_16_SMEM_16,

    // OP_PMOVMSKB:
    TB_INSTRUM_ID_PMOVMSK_DREG_4_SREG_8,
    TB_INSTRUM_ID_PMOVMSK_DREG_4_SREG_16,
    TB_INSTRUM_ID_PMOVMSK_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMOVMSK_DREG_8_SREG_16,

    // OP_PSUBUSB:

    // OP_PSUBUSW:

    // OP_PMINUB:
    TB_INSTRUM_ID_PMINUB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PMINUB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMINUB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMINUB_DREG_16_SREG_16,

    // OP_PAND:
    TB_INSTRUM_ID_PAND_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PAND_DREG_8_SREG_8,
    TB_INSTRUM_ID_PAND_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PAND_DREG_16_SREG_16,

    // OP_PADDUSB:

    // OP_PADDUSW:

    // OP_PMAXUB:
    TB_INSTRUM_ID_PMAXUB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PMAXUB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMAXUB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMAXUB_DREG_16_SREG_16,

    // OP_PANDN:
    TB_INSTRUM_ID_PANDN_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PANDN_DREG_8_SREG_8,
    TB_INSTRUM_ID_PANDN_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PANDN_DREG_16_SREG_16,

    // OP_PAVGB:

    // OP_PSRAW:
    TB_INSTRUM_ID_PSRAW_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSRAW_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSRAW_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSRAW_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSRAW_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSRAW_DREG_16_SREG_16_SIMM_1,

    // OP_PSRAD:
    TB_INSTRUM_ID_PSRAD_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSRAD_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSRAD_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSRAD_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSRAD_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSRAD_DREG_16_SREG_16_SIMM_1,

    // OP_PAVGW:

    // OP_PMULHUW:
    TB_INSTRUM_ID_PMULHUW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PMULHUW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMULHUW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMULHUW_DREG_16_SREG_16,

    // OP_PMULHW:
    TB_INSTRUM_ID_PMULHW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PMULHW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMULHW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMULHW_DREG_16_SREG_16,

    // OP_MOVNTQ:
    // OP_MOVNTDQ:
    // OP_PSUBSB:

    // OP_PSUBSW:

    // OP_PMINSW:
    TB_INSTRUM_ID_PMINSW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PMINSW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMINSW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMINSW_DREG_16_SREG_16,

    // OP_POR:
    TB_INSTRUM_ID_POR_DREG_8_SMEM_8,
    TB_INSTRUM_ID_POR_DREG_8_SREG_8,
    TB_INSTRUM_ID_POR_DREG_16_SMEM_16,
    TB_INSTRUM_ID_POR_DREG_16_SREG_16,

    // OP_PADDSB:

    // OP_PADDSW:

    // OP_PMAXSW:
    TB_INSTRUM_ID_PMAXSW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PMAXSW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PMAXSW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMAXSW_DREG_16_SREG_16,

    // OP_PXOR:
    TB_INSTRUM_ID_PXOR_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PXOR_DREG_8_SREG_8,
    TB_INSTRUM_ID_PXOR_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PXOR_DREG_16_SREG_16,

    // OP_PSLLW:
    TB_INSTRUM_ID_PSLLW_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSLLW_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSLLW_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSLLW_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSLLW_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSLLW_DREG_16_SREG_16_SIMM_1,

    // OP_PSLLD:
    TB_INSTRUM_ID_PSLLD_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSLLD_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSLLD_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSLLD_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSLLD_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSLLD_DREG_16_SREG_16_SIMM_1,

    // OP_PSLLQ:
    TB_INSTRUM_ID_PSLLQ_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PSLLQ_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PSLLQ_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PSLLQ_DREG_16_SREG_16_SMEM_16,
    TB_INSTRUM_ID_PSLLQ_DREG_8_SREG_8_SIMM_1,
    TB_INSTRUM_ID_PSLLQ_DREG_16_SREG_16_SIMM_1,

    // OP_PMULUDQ:

    // OP_PMADDWD:
    TB_INSTRUM_ID_PMADDWD_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PMADDWD_DREG_16_SREG_16_SREG_16,
    TB_INSTRUM_ID_PMADDWD_DREG_8_SREG_8_SMEM_8,
    TB_INSTRUM_ID_PMADDWD_DREG_16_SREG_16_SMEM_16,

    // OP_PSADBW:
    // OP_MASKMOVQ:
    // OP_MASKMOVDQU:

    // OP_PSUBB:
    TB_INSTRUM_ID_PSUBB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PSUBB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PSUBB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PSUBB_DREG_16_SREG_16,

    // OP_PSUBW:
    TB_INSTRUM_ID_PSUBW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PSUBW_DREG_16_SREG_16,
    TB_INSTRUM_ID_PSUBW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PSUBW_DREG_16_SMEM_16,

    // OP_PSUBD:
    TB_INSTRUM_ID_PSUBD_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PSUBD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PSUBD_DREG_8_SREG_8,
    TB_INSTRUM_ID_PSUBD_DREG_16_SREG_16,

    // OP_PSUBQ:
    TB_INSTRUM_ID_PSUBQ_DREG_8_SREG_8,
    TB_INSTRUM_ID_PSUBQ_DREG_16_SREG_16,
    TB_INSTRUM_ID_PSUBQ_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PSUBQ_DREG_16_SMEM_16,

    // OP_PADDB:
    TB_INSTRUM_ID_PADDB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PADDB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PADDB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PADDB_DREG_16_SREG_16,

    // OP_PADDW:
    TB_INSTRUM_ID_PADDW_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PADDW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PADDW_DREG_8_SREG_8,
    TB_INSTRUM_ID_PADDW_DREG_16_SREG_16,

    // OP_PADDD:
    TB_INSTRUM_ID_PADDD_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PADDD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PADDD_DREG_8_SREG_8,
    TB_INSTRUM_ID_PADDD_DREG_16_SREG_16,

    // OP_PSRLDQ:
    TB_INSTRUM_ID_PSRLDQ_DREG_16_SREG_16_SIMM_1,

    // OP_PSLLDQ:
    TB_INSTRUM_ID_PSLLDQ_DREG_16_SREG_16_SIMM_1,

    // OP_ROL:
    TB_INSTRUM_ID_ROL_SOLE_DREG_1,
    TB_INSTRUM_ID_ROL_SOLE_DREG_2,
    TB_INSTRUM_ID_ROL_SOLE_DREG_4,
    TB_INSTRUM_ID_ROL_SOLE_DREG_8,
    TB_INSTRUM_ID_ROL_DREG_1_IMM_1,
    TB_INSTRUM_ID_ROL_DREG_2_IMM_1,
    TB_INSTRUM_ID_ROL_DREG_4_IMM_1,
    TB_INSTRUM_ID_ROL_DREG_8_IMM_1,
    TB_INSTRUM_ID_ROL_DREG_1_REG_1,
    TB_INSTRUM_ID_ROL_DREG_2_REG_1,
    TB_INSTRUM_ID_ROL_DREG_4_REG_1,
    TB_INSTRUM_ID_ROL_DREG_8_REG_1,

    TB_INSTRUM_ID_ROL_SOLE_DMEM_1,
    TB_INSTRUM_ID_ROL_SOLE_DMEM_2,
    TB_INSTRUM_ID_ROL_SOLE_DMEM_4,
    TB_INSTRUM_ID_ROL_SOLE_DMEM_8,
    TB_INSTRUM_ID_ROL_DMEM_1_IMM_1,
    TB_INSTRUM_ID_ROL_DMEM_2_IMM_1,
    TB_INSTRUM_ID_ROL_DMEM_4_IMM_1,
    TB_INSTRUM_ID_ROL_DMEM_8_IMM_1,
    TB_INSTRUM_ID_ROL_DMEM_1_REG_1,
    TB_INSTRUM_ID_ROL_DMEM_2_REG_1,
    TB_INSTRUM_ID_ROL_DMEM_4_REG_1,
    TB_INSTRUM_ID_ROL_DMEM_8_REG_1,

    // OP_ROR:
    TB_INSTRUM_ID_ROR_SOLE_DREG_1,
    TB_INSTRUM_ID_ROR_SOLE_DREG_2,
    TB_INSTRUM_ID_ROR_SOLE_DREG_4,
    TB_INSTRUM_ID_ROR_SOLE_DREG_8,
    TB_INSTRUM_ID_ROR_DREG_1_IMM_1,
    TB_INSTRUM_ID_ROR_DREG_2_IMM_1,
    TB_INSTRUM_ID_ROR_DREG_4_IMM_1,
    TB_INSTRUM_ID_ROR_DREG_8_IMM_1,
    TB_INSTRUM_ID_ROR_DREG_1_REG_1,
    TB_INSTRUM_ID_ROR_DREG_2_REG_1,
    TB_INSTRUM_ID_ROR_DREG_4_REG_1,
    TB_INSTRUM_ID_ROR_DREG_8_REG_1,

    TB_INSTRUM_ID_ROR_SOLE_DMEM_1,
    TB_INSTRUM_ID_ROR_SOLE_DMEM_2,
    TB_INSTRUM_ID_ROR_SOLE_DMEM_4,
    TB_INSTRUM_ID_ROR_SOLE_DMEM_8,
    TB_INSTRUM_ID_ROR_DMEM_1_IMM_1,
    TB_INSTRUM_ID_ROR_DMEM_2_IMM_1,
    TB_INSTRUM_ID_ROR_DMEM_4_IMM_1,
    TB_INSTRUM_ID_ROR_DMEM_8_IMM_1,
    TB_INSTRUM_ID_ROR_DMEM_1_REG_1,
    TB_INSTRUM_ID_ROR_DMEM_2_REG_1,
    TB_INSTRUM_ID_ROR_DMEM_4_REG_1,
    TB_INSTRUM_ID_ROR_DMEM_8_REG_1,

    // OP_RCL:
    TB_INSTRUM_ID_RCL_SOLE_DREG_1,
    TB_INSTRUM_ID_RCL_SOLE_DREG_2,
    TB_INSTRUM_ID_RCL_SOLE_DREG_4,
    TB_INSTRUM_ID_RCL_SOLE_DREG_8,
    TB_INSTRUM_ID_RCL_DREG_1_IMM_1,
    TB_INSTRUM_ID_RCL_DREG_2_IMM_1,
    TB_INSTRUM_ID_RCL_DREG_4_IMM_1,
    TB_INSTRUM_ID_RCL_DREG_8_IMM_1,
    TB_INSTRUM_ID_RCL_DREG_1_REG_1,
    TB_INSTRUM_ID_RCL_DREG_2_REG_1,
    TB_INSTRUM_ID_RCL_DREG_4_REG_1,
    TB_INSTRUM_ID_RCL_DREG_8_REG_1,

    TB_INSTRUM_ID_RCL_SOLE_DMEM_1,
    TB_INSTRUM_ID_RCL_SOLE_DMEM_2,
    TB_INSTRUM_ID_RCL_SOLE_DMEM_4,
    TB_INSTRUM_ID_RCL_SOLE_DMEM_8,
    TB_INSTRUM_ID_RCL_DMEM_1_IMM_1,
    TB_INSTRUM_ID_RCL_DMEM_2_IMM_1,
    TB_INSTRUM_ID_RCL_DMEM_4_IMM_1,
    TB_INSTRUM_ID_RCL_DMEM_8_IMM_1,
    TB_INSTRUM_ID_RCL_DMEM_1_REG_1,
    TB_INSTRUM_ID_RCL_DMEM_2_REG_1,
    TB_INSTRUM_ID_RCL_DMEM_4_REG_1,
    TB_INSTRUM_ID_RCL_DMEM_8_REG_1,

    // OP_RCR:
    TB_INSTRUM_ID_RCR_SOLE_DREG_1,
    TB_INSTRUM_ID_RCR_SOLE_DREG_2,
    TB_INSTRUM_ID_RCR_SOLE_DREG_4,
    TB_INSTRUM_ID_RCR_SOLE_DREG_8,
    TB_INSTRUM_ID_RCR_DREG_1_IMM_1,
    TB_INSTRUM_ID_RCR_DREG_2_IMM_1,
    TB_INSTRUM_ID_RCR_DREG_4_IMM_1,
    TB_INSTRUM_ID_RCR_DREG_8_IMM_1,
    TB_INSTRUM_ID_RCR_DREG_1_REG_1,
    TB_INSTRUM_ID_RCR_DREG_2_REG_1,
    TB_INSTRUM_ID_RCR_DREG_4_REG_1,
    TB_INSTRUM_ID_RCR_DREG_8_REG_1,

    TB_INSTRUM_ID_RCR_SOLE_DMEM_1,
    TB_INSTRUM_ID_RCR_SOLE_DMEM_2,
    TB_INSTRUM_ID_RCR_SOLE_DMEM_4,
    TB_INSTRUM_ID_RCR_SOLE_DMEM_8,
    TB_INSTRUM_ID_RCR_DMEM_1_IMM_1,
    TB_INSTRUM_ID_RCR_DMEM_2_IMM_1,
    TB_INSTRUM_ID_RCR_DMEM_4_IMM_1,
    TB_INSTRUM_ID_RCR_DMEM_8_IMM_1,
    TB_INSTRUM_ID_RCR_DMEM_1_REG_1,
    TB_INSTRUM_ID_RCR_DMEM_2_REG_1,
    TB_INSTRUM_ID_RCR_DMEM_4_REG_1,
    TB_INSTRUM_ID_RCR_DMEM_8_REG_1,

    // OP_SHL:
    TB_INSTRUM_ID_SHL_SOLE_DREG_1,
    TB_INSTRUM_ID_SHL_SOLE_DREG_2,
    TB_INSTRUM_ID_SHL_SOLE_DREG_4,
    TB_INSTRUM_ID_SHL_SOLE_DREG_8,
    TB_INSTRUM_ID_SHL_DREG_1_IMM_1,
    TB_INSTRUM_ID_SHL_DREG_2_IMM_1,
    TB_INSTRUM_ID_SHL_DREG_4_IMM_1,
    TB_INSTRUM_ID_SHL_DREG_8_IMM_1,
    TB_INSTRUM_ID_SHL_DREG_1_REG_1,
    TB_INSTRUM_ID_SHL_DREG_2_REG_1,
    TB_INSTRUM_ID_SHL_DREG_4_REG_1,
    TB_INSTRUM_ID_SHL_DREG_8_REG_1,

    TB_INSTRUM_ID_SHL_SOLE_DMEM_1,
    TB_INSTRUM_ID_SHL_SOLE_DMEM_2,
    TB_INSTRUM_ID_SHL_SOLE_DMEM_4,
    TB_INSTRUM_ID_SHL_SOLE_DMEM_8,
    TB_INSTRUM_ID_SHL_DMEM_1_IMM_1,
    TB_INSTRUM_ID_SHL_DMEM_2_IMM_1,
    TB_INSTRUM_ID_SHL_DMEM_4_IMM_1,
    TB_INSTRUM_ID_SHL_DMEM_8_IMM_1,
    TB_INSTRUM_ID_SHL_DMEM_1_REG_1,
    TB_INSTRUM_ID_SHL_DMEM_2_REG_1,
    TB_INSTRUM_ID_SHL_DMEM_4_REG_1,
    TB_INSTRUM_ID_SHL_DMEM_8_REG_1,

    // OP_SHR:
    TB_INSTRUM_ID_SHR_SOLE_DREG_1,
    TB_INSTRUM_ID_SHR_SOLE_DREG_2,
    TB_INSTRUM_ID_SHR_SOLE_DREG_4,
    TB_INSTRUM_ID_SHR_SOLE_DREG_8,
    TB_INSTRUM_ID_SHR_DREG_1_IMM_1,
    TB_INSTRUM_ID_SHR_DREG_2_IMM_1,
    TB_INSTRUM_ID_SHR_DREG_4_IMM_1,
    TB_INSTRUM_ID_SHR_DREG_8_IMM_1,
    TB_INSTRUM_ID_SHR_DREG_1_REG_1,
    TB_INSTRUM_ID_SHR_DREG_2_REG_1,
    TB_INSTRUM_ID_SHR_DREG_4_REG_1,
    TB_INSTRUM_ID_SHR_DREG_8_REG_1,

    TB_INSTRUM_ID_SHR_SOLE_DMEM_1,
    TB_INSTRUM_ID_SHR_SOLE_DMEM_2,
    TB_INSTRUM_ID_SHR_SOLE_DMEM_4,
    TB_INSTRUM_ID_SHR_SOLE_DMEM_8,

    TB_INSTRUM_ID_SHR_DMEM_1_IMM_1,
    TB_INSTRUM_ID_SHR_DMEM_2_IMM_1,
    TB_INSTRUM_ID_SHR_DMEM_4_IMM_1,
    TB_INSTRUM_ID_SHR_DMEM_8_IMM_1,

    TB_INSTRUM_ID_SHR_DMEM_1_REG_1,
    TB_INSTRUM_ID_SHR_DMEM_2_REG_1,
    TB_INSTRUM_ID_SHR_DMEM_4_REG_1,
    TB_INSTRUM_ID_SHR_DMEM_8_REG_1,

    // OP_SAR:
    TB_INSTRUM_ID_SAR_SOLE_DREG_1,
    TB_INSTRUM_ID_SAR_SOLE_DREG_2,
    TB_INSTRUM_ID_SAR_SOLE_DREG_4,
    TB_INSTRUM_ID_SAR_SOLE_DREG_8,
    TB_INSTRUM_ID_SAR_DREG_1_IMM_1,
    TB_INSTRUM_ID_SAR_DREG_2_IMM_1,
    TB_INSTRUM_ID_SAR_DREG_4_IMM_1,
    TB_INSTRUM_ID_SAR_DREG_8_IMM_1,
    TB_INSTRUM_ID_SAR_DREG_1_REG_1,
    TB_INSTRUM_ID_SAR_DREG_2_REG_1,
    TB_INSTRUM_ID_SAR_DREG_4_REG_1,
    TB_INSTRUM_ID_SAR_DREG_8_REG_1,

    TB_INSTRUM_ID_SAR_SOLE_DMEM_1,
    TB_INSTRUM_ID_SAR_SOLE_DMEM_2,
    TB_INSTRUM_ID_SAR_SOLE_DMEM_4,
    TB_INSTRUM_ID_SAR_SOLE_DMEM_8,
    TB_INSTRUM_ID_SAR_DMEM_1_IMM_1,
    TB_INSTRUM_ID_SAR_DMEM_2_IMM_1,
    TB_INSTRUM_ID_SAR_DMEM_4_IMM_1,
    TB_INSTRUM_ID_SAR_DMEM_8_IMM_1,
    TB_INSTRUM_ID_SAR_DMEM_1_REG_1,
    TB_INSTRUM_ID_SAR_DMEM_2_REG_1,
    TB_INSTRUM_ID_SAR_DMEM_4_REG_1,
    TB_INSTRUM_ID_SAR_DMEM_8_REG_1,

    // OP_NOT:
    TB_INSTRUM_ID_NOT_DMEM_1_DMEM_1,
    TB_INSTRUM_ID_NOT_DMEM_2_DMEM_2,
    TB_INSTRUM_ID_NOT_DMEM_4_DMEM_4,
    TB_INSTRUM_ID_NOT_DMEM_8_DMEM_8,
    TB_INSTRUM_ID_NOT_DREG_1_DREG_1,
    TB_INSTRUM_ID_NOT_DREG_2_DREG_2,
    TB_INSTRUM_ID_NOT_DREG_4_DREG_4,
    TB_INSTRUM_ID_NOT_DREG_8_DREG_8,

    // OP_NEG:
    TB_INSTRUM_ID_NEG_DMEM_1_DMEM_1,
    TB_INSTRUM_ID_NEG_DMEM_2_DMEM_2,
    TB_INSTRUM_ID_NEG_DMEM_4_DMEM_4,
    TB_INSTRUM_ID_NEG_DMEM_8_DMEM_8,
    TB_INSTRUM_ID_NEG_DREG_1_DREG_1,
    TB_INSTRUM_ID_NEG_DREG_2_DREG_2,
    TB_INSTRUM_ID_NEG_DREG_4_DREG_4,
    TB_INSTRUM_ID_NEG_DREG_8_DREG_8,

    // OP_MUL:
    TB_INSTRUM_ID_MUL_DREG_2_SREG_1_SREG_1,
    TB_INSTRUM_ID_MUL_DREG_2_SMEM_1_SREG_1,
    TB_INSTRUM_ID_MUL_DREG_4_DREG_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_MUL_DREG_4_DREG_4_SMEM_4_SREG_4,

    // OP_DIV:
    TB_INSTRUM_ID_DIV_DREG_4_DREG_4_SMEM_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_DIV_DREG_4_DREG_4_SREG_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_DIV_DREG_1_DREG_1_SREG_1_SREG_2,
    TB_INSTRUM_ID_DIV_DREG_1_DREG_1_SMEM_1_SREG_2,

    // OP_IDIV:
    TB_INSTRUM_ID_IDIV_DREG_4_DREG_4_SMEM_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_IDIV_DREG_4_DREG_4_SREG_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_IDIV_DREG_1_DREG_1_SREG_1_SREG_2,
    TB_INSTRUM_ID_IDIV_DREG_1_DREG_1_SMEM_1_SREG_2,

    // OP_SLDT:
    // OP_STR:
    // OP_LLDT:
    // OP_LTR:
    // OP_VERR:
    // OP_VERW:
    // OP_SGDT:
    // OP_SIDT:
    // OP_LGDT:
    // OP_LIDT:
    // OP_SMSW:
    // OP_LMSW:
    // OP_INVLPG:
    // OP_CMPXCHG8B:
    // OP_FXSAVE32:
    // OP_FXRSTOR32:
    // OP_LDMXCSR:
    // OP_STMXCSR:
    // OP_LFENCE:

    // OP_MFENCE:

    // OP_SFENCE:

    // OP_MOVUPS:
    TB_INSTRUM_ID_MOVUPS_DREG_16_SMEM_16,
    TB_INSTRUM_ID_MOVUPS_DMEM_16_SREG_16,
    TB_INSTRUM_ID_MOVUPS_DREG_16_SREG_16,

    // OP_MOVSS:

    // OP_MOVUPD:
    TB_INSTRUM_ID_MOVUPD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_MOVUPD_DMEM_16_SREG_16,
    TB_INSTRUM_ID_MOVUPD_DREG_16_SREG_16,

    // OP_MOVSD:

    // OP_MOVLPS:
    TB_INSTRUM_ID_MOVLPS_DREG_16_SMEM_8,
    TB_INSTRUM_ID_MOVLPS_DMEM_8_SREG_16,

    TB_INSTRUM_ID_MOVLPD_DREG_16_SMEM_8,
    TB_INSTRUM_ID_MOVLPD_DMEM_8_SREG_16,

    // OP_UNPCKLPS:
    // OP_UNPCKLPD:
    // OP_UNPCKHPS:
    // OP_UNPCKHPD:
    // OP_MOVHPS:
    // OP_MOVHPD:
    // OP_MOVAPS:
    TB_INSTRUM_ID_MOVAPS_DREG_16_SMEM_16,
    TB_INSTRUM_ID_MOVAPS_DMEM_16_SREG_16,
    TB_INSTRUM_ID_MOVAPS_DREG_16_SREG_16,

    // OP_MOVAPD:
    // OP_CVTPI2PS:
    // OP_CVTSI2SS:
    // OP_CVTPI2PD:
    // OP_CVTSI2SD:
    // OP_CVTTPS2PI:
    // OP_CVTTSS2SI:
    // OP_CVTTPD2PI:
    // OP_CVTTSD2SI:
    // OP_CVTPS2PI:
    // OP_CVTSS2SI:
    // OP_CVTPD2PI:
    // OP_CVTSD2SI:
    // OP_UCOMISS:
    // OP_UCOMISD:
    // OP_COMISS:
    // OP_COMISD:
    // OP_MOVMSKPS:
    // OP_MOVMSKPD:
    // OP_SQRTPS:
    // OP_SQRTSS:
    // OP_SQRTPD:
    // OP_SQRTSD:
    // OP_RSQRTPS:
    // OP_RSQRTSS:
    // OP_RCPPS:
    // OP_RCPSS:
    // OP_ANDPS:
    TB_INSTRUM_ID_ANDPS_DREG_16_SREG_16,
    TB_INSTRUM_ID_ANDPS_DREG_16_SMEM_16,

    // OP_ANDPD:
    TB_INSTRUM_ID_ANDPD_DREG_16_SREG_16,
    TB_INSTRUM_ID_ANDPD_DREG_16_SMEM_16,

    // OP_ANDNPS:
    TB_INSTRUM_ID_ANDNPS_DREG_16_SREG_16,
    TB_INSTRUM_ID_ANDNPS_DREG_16_SMEM_16,

    // OP_ANDNPD:
    TB_INSTRUM_ID_ANDNPD_DREG_16_SREG_16,
    TB_INSTRUM_ID_ANDNPD_DREG_16_SMEM_16,

    // OP_ORPS:
    TB_INSTRUM_ID_ORPS_DREG_16_SREG_16,
    TB_INSTRUM_ID_ORPS_DREG_16_SMEM_16,

    // OP_ORPD:
    TB_INSTRUM_ID_ORPD_DREG_16_SREG_16,
    TB_INSTRUM_ID_ORPD_DREG_16_SMEM_16,

    // OP_XORPS:
    TB_INSTRUM_ID_XORPS_DREG_16_SREG_16,
    TB_INSTRUM_ID_XORPS_DREG_16_SMEM_16,

    // OP_XORPD:
    TB_INSTRUM_ID_XORPD_DREG_16_SREG_16,
    TB_INSTRUM_ID_XORPD_DREG_16_SMEM_16,

    // OP_ADDPS:
    // OP_ADDSS:
    // OP_ADDPD:
    // OP_ADDSD:
    // OP_MULPS:
    // OP_MULSS:
    // OP_MULPD:
    // OP_MULSD:
    // OP_CVTPS2PD:
    // OP_CVTSS2SD:
    // OP_CVTPD2PS:
    // OP_CVTSD2SS:
    // OP_CVTDQ2PS:
    // OP_CVTTPS2DQ:
    // OP_CVTPS2DQ:
    // OP_SUBPS:
    // OP_SUBSS:
    // OP_SUBPD:
    // OP_SUBSD:
    // OP_MINPS:
    // OP_MINSS:
    // OP_MINPD:
    // OP_MINSD:
    // OP_DIVPS:
    // OP_DIVSS:
    // OP_DIVPD:
    // OP_DIVSD:
    // OP_MAXPS:
    // OP_MAXSS:
    // OP_MAXPD:
    // OP_MAXSD:
    // OP_CMPPS:
    // OP_CMPSS:
    // OP_CMPPD:
    // OP_CMPSD:
    // OP_SHUFPS:
    // OP_SHUFPD:
    // OP_CVTDQ2PD:
    // OP_CVTTPD2DQ:
    // OP_CVTPD2DQ:

    // OP_PAUSE:

    // OP_INS:
    // OP_REP_INS:
    // OP_OUTS:
    // OP_REP_OUTS:

    // OP_MOVS:
    TB_INSTRUM_ID_MOVS_DMEM_1_SMEM_1,
    TB_INSTRUM_ID_MOVS_DMEM_2_SMEM_2,
    TB_INSTRUM_ID_MOVS_DMEM_4_SMEM_4,
    TB_INSTRUM_ID_MOVS_DMEM_8_SMEM_8,

    // OP_REP_MOVS:
    TB_INSTRUM_ID_REP_MOVSB,
    TB_INSTRUM_ID_REP_MOVSW,
    TB_INSTRUM_ID_REP_MOVSD,
    TB_INSTRUM_ID_REP_MOVSQ,

    // OP_STOS:
    TB_INSTRUM_ID_STOS_DMEM_1_SREG_1,
    TB_INSTRUM_ID_STOS_DMEM_2_SREG_2,
    TB_INSTRUM_ID_STOS_DMEM_4_SREG_4,
    TB_INSTRUM_ID_STOS_DMEM_8_SREG_8,

    // OP_REP_STOS:
    TB_INSTRUM_ID_REP_STOSB,
    TB_INSTRUM_ID_REP_STOSW,
    TB_INSTRUM_ID_REP_STOSD,
    TB_INSTRUM_ID_REP_STOSQ,

    // OP_LODS:
    // OP_REP_LODS:

    // OP_REP_CMPS:

    // OP_REPNE_CMPS:

    // OP_FADD:
    // OP_FMUL:
    // OP_FCOM:
    // OP_FCOMP:
    // OP_FSUB:
    // OP_FSUBR:
    // OP_FDIV:
    // OP_FDIVR:
    // OP_FLD:
    // OP_FST:
    // OP_FSTP:
    // OP_FLDENV:
    // OP_FLDCW:
    // OP_FNSTENV:
    // OP_FNSTCW:
    // OP_FIADD:
    // OP_FIMUL:
    // OP_FICOM:
    // OP_FICOMP:
    // OP_FISUB:
    // OP_FISUBR:
    // OP_FIDIV:
    // OP_FIDIVR:
    // OP_FILD:
    // OP_FIST:
    // OP_FISTP:
    // OP_FRSTOR:
    // OP_FNSAVE:
    // OP_FNSTSW:

    // OP_FBLD:
    // OP_FBSTP:

    // OP_FXCH:

    // OP_FCHS:
    // OP_FABS:
    // OP_FTST:
    // OP_FXAM:
    // OP_FLD1:
    // OP_FLDL2T:
    // OP_FLDL2E:
    // OP_FLDPI:
    // OP_FLDLG2:
    // OP_FLDLN2:
    // OP_FLDZ:
    // OP_F2XM1:
    // OP_FYL2X:
    // OP_FPTAN:
    // OP_FPATAN:
    // OP_FXTRACT:
    // OP_FPREM1:
    // OP_FDECSTP:
    // OP_FINCSTP:
    // OP_FPREM:
    // OP_FYL2XP1:
    // OP_FSQRT:
    // OP_FSINCOS:
    // OP_FRNDINT:
    // OP_FSCALE:
    // OP_FSIN:
    // OP_FCOS:
    // OP_FCMOVB:
    // OP_FCMOVE:
    // OP_FCMOVBE:
    // OP_FCMOVU:
    // OP_FUCOMPP:
    // OP_FCMOVNB:
    // OP_FCMOVNE:
    // OP_FCMOVNBE:
    // OP_FCMOVNU:
    // OP_FNCLEX:
    // OP_FNINIT:
    // OP_FUCOMI:
    // OP_FCOMI:
    // OP_FFREE:
    // OP_FUCOM:
    // OP_FUCOMP:
    // OP_FADDP:
    // OP_FMULP:
    // OP_FCOMPP:
    // OP_FSUBRP:
    // OP_FSUBP:
    // OP_FDIVRP:
    // OP_FDIVP:
    // OP_FUCOMIP:
    // OP_FCOMIP:

    // OP_FISTTP:
    // OP_HADDPD:
    // OP_HADDPS:
    // OP_HSUBPD:
    // OP_HSUBPS:
    // OP_ADDSUBPD:
    // OP_ADDSUBPS:
    // OP_LDDQU:
    TB_INSTRUM_ID_LDDQU_DREG_16_SMEM_16,

    // OP_MONITOR:
    // OP_MWAIT:
    // OP_MOVSLDUP:
    // OP_MOVSHDUP:
    // OP_MOVDDUP:

    // OP_FEMMS:
    // OP_UNKNOWN_3DNOW:
    // OP_PAVGUSB:
    // OP_PFADD:
    // OP_PFACC:
    // OP_PFCMPGE:
    // OP_PFCMPGT:
    // OP_PFCMPEQ:
    // OP_PFMIN:
    // OP_PFMAX:
    // OP_PFMUL:
    // OP_PFRCP:
    // OP_PFRCPIT1:
    // OP_PFRCPIT2:
    // OP_PFRSQRT:
    // OP_PFRSQIT1:
    // OP_PMULHRW:
    // OP_PFSUB:
    // OP_PFSUBR:
    // OP_PI2FD:
    // OP_PF2ID:
    // OP_PI2FW:
    // OP_PF2IW:
    // OP_PFNACC:
    // OP_PFPNACC:
    // OP_PSWAPD:

    // OP_PSHUFB:
    TB_INSTRUM_ID_PSHUFB_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PSHUFB_DREG_8_SREG_8,
    TB_INSTRUM_ID_PSHUFB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PSHUFB_DREG_16_SREG_16,

    // OP_PHADDW:
    // OP_PHADDD:
    // OP_PHADDSW:
    // OP_PMADDUBSW:
    // OP_PHSUBW:
    // OP_PHSUBD:
    // OP_PHSUBSW:
    // OP_PSIGNB:
    // OP_PSIGNW:
    // OP_PSIGND:
    // OP_PMULHRSW:
    // OP_PABSB:
    // OP_PABSW:
    // OP_PABSD:

    // OP_PALIGNR:
    TB_INSTRUM_ID_PALIGNR_DREG_8_SREG_8,
    TB_INSTRUM_ID_PALIGNR_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PALIGNR_DREG_16_SREG_16,
    TB_INSTRUM_ID_PALIGNR_DREG_16_SMEM_16,

    // OP_POPCNT:
    TB_INSTRUM_ID_POPCNT_DREG_2_SREG_2,
    TB_INSTRUM_ID_POPCNT_DREG_2_SMEM_2,
    TB_INSTRUM_ID_POPCNT_DREG_4_SREG_4,
    TB_INSTRUM_ID_POPCNT_DREG_4_SMEM_4,
    TB_INSTRUM_ID_POPCNT_DREG_8_SREG_8,
    TB_INSTRUM_ID_POPCNT_DREG_8_SMEM_8,

    // OP_MOVNTSS:
    // OP_MOVNTSD:
    // OP_EXTRQ:
    // OP_INSERTQ:
    // OP_LZCNT:
    TB_INSTRUM_ID_LZCNT_DREG_2_SMEM_2,
    TB_INSTRUM_ID_LZCNT_DREG_4_SMEM_4,
    TB_INSTRUM_ID_LZCNT_DREG_8_SMEM_8,
    TB_INSTRUM_ID_LZCNT_DREG_2_SREG_2,
    TB_INSTRUM_ID_LZCNT_DREG_4_SREG_4,
    TB_INSTRUM_ID_LZCNT_DREG_8_SREG_8,

    // OP_PBLENDVB:
    // OP_BLENDVPS:
    // OP_BLENDVPD:

    // OP_PMOVSXBW:
    // OP_PMOVSXBD:
    // OP_PMOVSXBQ:
    // OP_PMOVSXWD:
    // OP_PMOVSXWQ:
    // OP_PMOVSXDQ:
    // OP_PMULDQ:

    // OP_PCMPEQQ:
    TB_INSTRUM_ID_PCMPEQQ_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPEQQ_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPEQQ_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPEQQ_DREG_16_SREG_16,

    // OP_MOVNTDQA:
    // OP_PACKUSDW:
    TB_INSTRUM_ID_PACKUSDW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PACKUSDW_DREG_16_SREG_16,

    // OP_PMOVZXBW:
    // OP_PMOVZXBD:
    // OP_PMOVZXBQ:
    // OP_PMOVZXWD:
    // OP_PMOVZXWQ:
    // OP_PMOVZXDQ:

    // OP_PCMPGTQ:
    TB_INSTRUM_ID_PCMPGTQ_DREG_8_SMEM_8,
    TB_INSTRUM_ID_PCMPGTQ_DREG_8_SREG_8,
    TB_INSTRUM_ID_PCMPGTQ_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PCMPGTQ_DREG_16_SREG_16,

    // OP_PMINSB:
    TB_INSTRUM_ID_PMINSB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMINSB_DREG_16_SREG_16,

    // OP_PMINSD:
    TB_INSTRUM_ID_PMINSD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMINSD_DREG_16_SREG_16,

    // OP_PMINUW:
    TB_INSTRUM_ID_PMINUW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMINUW_DREG_16_SREG_16,

    // OP_PMINUD:
    TB_INSTRUM_ID_PMINUD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMINUD_DREG_16_SREG_16,

    // OP_PMAXSB:
    TB_INSTRUM_ID_PMAXSB_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMAXSB_DREG_16_SREG_16,

    // OP_PMAXSD:
    TB_INSTRUM_ID_PMAXSD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMAXSD_DREG_16_SREG_16,

    // OP_PMAXUW:
    TB_INSTRUM_ID_PMAXUW_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMAXUW_DREG_16_SREG_16,

    // OP_PMAXUD:
    TB_INSTRUM_ID_PMAXUD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMAXUD_DREG_16_SREG_16,

    // OP_PMULLD:
    TB_INSTRUM_ID_PMULLD_DREG_16_SMEM_16,
    TB_INSTRUM_ID_PMULLD_DREG_16_SREG_16,

    // OP_PHMINPOSUW:
    // OP_CRC32:

    // OP_PEXTRB:
    TB_INSTRUM_ID_PEXTRB_DREG_4,
    TB_INSTRUM_ID_PEXTRB_DMEM_4,

    // OP_PEXTRD:
    TB_INSTRUM_ID_PEXTRD_DREG_4,
    TB_INSTRUM_ID_PEXTRD_DMEM_4,

    // OP_EXTRACTPS:
    // OP_ROUNDPS:
    // OP_ROUNDPD:
    // OP_ROUNDSS:
    // OP_ROUNDSD:
    // OP_BLENDPS:
    // OP_BLENDPD:
    // OP_PBLENDW:
    // OP_PINSRB:
    // OP_INSERTPS:
    // OP_PINSRD:
    // OP_DPPS:
    // OP_DPPD:
    // OP_MPSADBW:
    // OP_PCMPESTRM:
    // OP_PCMPESTRI:
    // OP_PCMPISTRM:
    // OP_PCMPISTRI:

    // OP_MOVSXD:
    // OP_SWAPGS:

    // OP_VMCALL:
    // OP_VMLAUNCH:
    // OP_VMRESUME:
    // OP_VMXOFF:
    // OP_VMPTRST:
    // OP_VMPTRLD:
    // OP_VMXON:
    // OP_VMCLEAR:
    // OP_VMREAD:
    // OP_VMWRITE:

    // OP_INT1:
    // OP_SALC:
    // OP_FFREEP:

    // OP_VMRUN:
    // OP_VMMCALL:
    // OP_VMLOAD:
    // OP_VMSAVE:
    // OP_STGI:
    // OP_CLGI:
    // OP_SKINIT:
    // OP_INVLPGA:

    // OP_RDTSCP:

    // OP_INVEPT:
    // OP_INVVPID:

    // OP_PCLMULQDQ:
    // OP_AESIMC:
    // OP_AESENC:
    // OP_AESENCLAST:
    // OP_AESDEC:
    // OP_AESDECLAST:
    // OP_AESKEYGENASSIST:

    // OP_MOVBE:

    // OP_XGETBV:
    // OP_XSETBV:
    // OP_XSAVE32:
    // OP_XRSTOR32:
    // OP_XSAVE// OPT32:

    // OP_VMOVSS:
    // OP_VMOVSD:
    // OP_VMOVUPS:
    // OP_VMOVUPD:
    // OP_VMOVLPS:
    // OP_VMOVSLDUP:
    // OP_VMOVLPD:
    // OP_VMOVDDUP:
    // OP_VUNPCKLPS:
    // OP_VUNPCKLPD:
    // OP_VUNPCKHPS:
    // OP_VUNPCKHPD:
    // OP_VMOVHPS:
    // OP_VMOVSHDUP:
    // OP_VMOVHPD:
    // OP_VMOVAPS:
    // OP_VMOVAPD:
    // OP_VCVTSI2SS:
    // OP_VCVTSI2SD:
    // OP_VMOVNTPS:
    // OP_VMOVNTPD:
    // OP_VCVTTSS2SI:
    // OP_VCVTTSD2SI:
    // OP_VCVTSS2SI:
    // OP_VCVTSD2SI:
    // OP_VUCOMISS:
    // OP_VUCOMISD:
    // OP_VCOMISS:
    // OP_VCOMISD:
    // OP_VMOVMSKPS:
    // OP_VMOVMSKPD:
    // OP_VSQRTPS:
    // OP_VSQRTSS:
    // OP_VSQRTPD:
    // OP_VSQRTSD:
    // OP_VRSQRTPS:
    // OP_VRSQRTSS:
    // OP_VRCPPS:
    // OP_VRCPSS:
    // OP_VANDPS:
    // OP_VANDPD:
    // OP_VANDNPS:
    // OP_VANDNPD:
    // OP_VORPS:
    // OP_VORPD:
    // OP_VXORPS:
    // OP_VXORPD:
    // OP_VADDPS:
    // OP_VADDSS:
    // OP_VADDPD:
    // OP_VADDSD:
    // OP_VMULPS:
    // OP_VMULSS:
    // OP_VMULPD:
    // OP_VMULSD:
    // OP_VCVTPS2PD:
    // OP_VCVTSS2SD:
    // OP_VCVTPD2PS:
    // OP_VCVTSD2SS:
    // OP_VCVTDQ2PS:
    // OP_VCVTTPS2DQ:
    // OP_VCVTPS2DQ:
    // OP_VSUBPS:
    // OP_VSUBSS:
    // OP_VSUBPD:
    // OP_VSUBSD:
    // OP_VMINPS:
    // OP_VMINSS:
    // OP_VMINPD:
    // OP_VMINSD:
    // OP_VDIVPS:
    // OP_VDIVSS:
    // OP_VDIVPD:
    // OP_VDIVSD:
    // OP_VMAXPS:
    // OP_VMAXSS:
    // OP_VMAXPD:
    // OP_VMAXSD:
    // OP_VPUNPCKLBW:
    // OP_VPUNPCKLWD:
    // OP_VPUNPCKLDQ:
    // OP_VPACKSSWB:
    // OP_VPCMPGTB:
    // OP_VPCMPGTW:
    // OP_VPCMPGTD:
    // OP_VPACKUSWB:
    // OP_VPUNPCKHBW:
    // OP_VPUNPCKHWD:
    // OP_VPUNPCKHDQ:
    // OP_VPACKSSDW:
    // OP_VPUNPCKLQDQ:
    // OP_VPUNPCKHQDQ:
    // OP_VMOVD:
    // OP_VPSHUFHW:
    // OP_VPSHUFD:
    // OP_VPSHUFLW:
    // OP_VPCMPEQB:
    // OP_VPCMPEQW:
    // OP_VPCMPEQD:
    // OP_VMOVQ:
    // OP_VCMPPS:
    // OP_VCMPSS:
    // OP_VCMPPD:
    // OP_VCMPSD:
    // OP_VPINSRW:
    // OP_VPEXTRW:
    // OP_VSHUFPS:
    // OP_VSHUFPD:
    // OP_VPSRLW:
    // OP_VPSRLD:
    // OP_VPSRLQ:
    // OP_VPADDQ:
    // OP_VPMULLW:
    // OP_VPMOVMSKB:
    // OP_VPSUBUSB:
    // OP_VPSUBUSW:
    // OP_VPMINUB:
    // OP_VPAND:
    // OP_VPADDUSB:
    // OP_VPADDUSW:
    // OP_VPMAXUB:
    // OP_VPANDN:
    // OP_VPAVGB:
    // OP_VPSRAW:
    // OP_VPSRAD:
    // OP_VPAVGW:
    // OP_VPMULHUW:
    // OP_VPMULHW:
    // OP_VCVTDQ2PD:
    // OP_VCVTTPD2DQ:
    // OP_VCVTPD2DQ:
    // OP_VMOVNTDQ:
    // OP_VPSUBSB:
    // OP_VPSUBSW:
    // OP_VPMINSW:
    // OP_VPOR:
    // OP_VPADDSB:
    // OP_VPADDSW:
    // OP_VPMAXSW:
    // OP_VPXOR:
    // OP_VPSLLW:
    // OP_VPSLLD:
    // OP_VPSLLQ:
    // OP_VPMULUDQ:
    // OP_VPMADDWD:
    // OP_VPSADBW:
    // OP_VMASKMOVDQU:
    // OP_VPSUBB:
    // OP_VPSUBW:
    // OP_VPSUBD:
    // OP_VPSUBQ:
    // OP_VPADDB:
    // OP_VPADDW:
    // OP_VPADDD:
    // OP_VPSRLDQ:
    // OP_VPSLLDQ:
    // OP_VMOVDQU:
    // OP_VMOVDQA:
    // OP_VHADDPD:
    // OP_VHADDPS:
    // OP_VHSUBPD:
    // OP_VHSUBPS:
    // OP_VADDSUBPD:
    // OP_VADDSUBPS:
    // OP_VLDDQU:
    // OP_VPSHUFB:
    // OP_VPHADDW:
    // OP_VPHADDD:
    // OP_VPHADDSW:
    // OP_VPMADDUBSW:
    // OP_VPHSUBW:
    // OP_VPHSUBD:
    // OP_VPHSUBSW:
    // OP_VPSIGNB:
    // OP_VPSIGNW:
    // OP_VPSIGND:
    // OP_VPMULHRSW:
    // OP_VPABSB:
    // OP_VPABSW:
    // OP_VPABSD:
    // OP_VPALIGNR:
    // OP_VPBLENDVB:
    // OP_VBLENDVPS:
    // OP_VBLENDVPD:
    // OP_VPTEST:
    // OP_VPMOVSXBW:
    // OP_VPMOVSXBD:
    // OP_VPMOVSXBQ:
    // OP_VPMOVSXWD:
    // OP_VPMOVSXWQ:
    // OP_VPMOVSXDQ:
    // OP_VPMULDQ:
    // OP_VPCMPEQQ:
    // OP_VMOVNTDQA:
    // OP_VPACKUSDW:
    // OP_VPMOVZXBW:
    // OP_VPMOVZXBD:
    // OP_VPMOVZXBQ:
    // OP_VPMOVZXWD:
    // OP_VPMOVZXWQ:
    // OP_VPMOVZXDQ:
    // OP_VPCMPGTQ:
    // OP_VPMINSB:
    // OP_VPMINSD:
    // OP_VPMINUW:
    // OP_VPMINUD:
    // OP_VPMAXSB:
    // OP_VPMAXSD:
    // OP_VPMAXUW:
    // OP_VPMAXUD:
    // OP_VPMULLD:
    // OP_VPHMINPOSUW:
    // OP_VAESIMC:
    // OP_VAESENC:
    // OP_VAESENCLAST:
    // OP_VAESDEC:
    // OP_VAESDECLAST:
    // OP_VPEXTRB:
    // OP_VPEXTRD:
    // OP_VEXTRACTPS:
    // OP_VROUNDPS:
    // OP_VROUNDPD:
    // OP_VROUNDSS:
    // OP_VROUNDSD:
    // OP_VBLENDPS:
    // OP_VBLENDPD:
    // OP_VPBLENDW:
    // OP_VPINSRB:
    // OP_VINSERTPS:
    // OP_VPINSRD:
    // OP_VDPPS:
    // OP_VDPPD:
    // OP_VMPSADBW:
    // OP_VPCMPESTRM:
    // OP_VPCMPESTRI:
    // OP_VPCMPISTRM:
    // OP_VPCMPISTRI:
    // OP_VPCLMULQDQ:
    // OP_VAESKEYGENASSIST:
    // OP_VTESTPS:
    // OP_VTESTPD:
    // OP_VZEROUPPER:
    // OP_VZEROALL:
    // OP_VLDMXCSR:
    // OP_VSTMXCSR:
    // OP_VBROADCASTSS:
    // OP_VBROADCASTSD:
    // OP_VBROADCASTF128:
    // OP_VMASKMOVPS:
    // OP_VMASKMOVPD:
    // OP_VPERMILPS:
    // OP_VPERMILPD:
    // OP_VPERM2F128:
    // OP_VINSERTF128:
    // OP_VEXTRACTF128:

    // OP_VCVTPH2PS:
    // OP_VCVTPS2PH:

    // OP_VFMADD132PS:
    // OP_VFMADD132PD:
    // OP_VFMADD213PS:
    // OP_VFMADD213PD:
    // OP_VFMADD231PS:
    // OP_VFMADD231PD:
    // OP_VFMADD132SS:
    // OP_VFMADD132SD:
    // OP_VFMADD213SS:
    // OP_VFMADD213SD:
    // OP_VFMADD231SS:
    // OP_VFMADD231SD:
    // OP_VFMADDSUB132PS:
    // OP_VFMADDSUB132PD:
    // OP_VFMADDSUB213PS:
    // OP_VFMADDSUB213PD:
    // OP_VFMADDSUB231PS:
    // OP_VFMADDSUB231PD:
    // OP_VFMSUBADD132PS:
    // OP_VFMSUBADD132PD:
    // OP_VFMSUBADD213PS:
    // OP_VFMSUBADD213PD:
    // OP_VFMSUBADD231PS:
    // OP_VFMSUBADD231PD:
    // OP_VFMSUB132PS:
    // OP_VFMSUB132PD:
    // OP_VFMSUB213PS:
    // OP_VFMSUB213PD:
    // OP_VFMSUB231PS:
    // OP_VFMSUB231PD:
    // OP_VFMSUB132SS:
    // OP_VFMSUB132SD:
    // OP_VFMSUB213SS:
    // OP_VFMSUB213SD:
    // OP_VFMSUB231SS:
    // OP_VFMSUB231SD:
    // OP_VFNMADD132PS:
    // OP_VFNMADD132PD:
    // OP_VFNMADD213PS:
    // OP_VFNMADD213PD:
    // OP_VFNMADD231PS:
    // OP_VFNMADD231PD:
    // OP_VFNMADD132SS:
    // OP_VFNMADD132SD:
    // OP_VFNMADD213SS:
    // OP_VFNMADD213SD:
    // OP_VFNMADD231SS:
    // OP_VFNMADD231SD:
    // OP_VFNMSUB132PS:
    // OP_VFNMSUB132PD:
    // OP_VFNMSUB213PS:
    // OP_VFNMSUB213PD:
    // OP_VFNMSUB231PS:
    // OP_VFNMSUB231PD:
    // OP_VFNMSUB132SS:
    // OP_VFNMSUB132SD:
    // OP_VFNMSUB213SS:
    // OP_VFNMSUB213SD:
    // OP_VFNMSUB231SS:
    // OP_VFNMSUB231SD:

    // OP_MOVQ2DQ:
    TB_INSTRUM_ID_MOVQ2DQ_DREG_16_SREG_8,

    // OP_MOVDQ2Q:
    TB_INSTRUM_ID_MOVDQ2Q_DREG_8_SREG_16,

    // OP_FXSAVE64:
    // OP_FXRSTOR64:
    // OP_XSAVE64:
    // OP_XRSTOR64:
    // OP_XSAVE// OPT64:

    // OP_RDRAND:
    // OP_RDFSBASE:
    // OP_RDGSBASE:
    // OP_WRFSBASE:
    // OP_WRGSBASE:

    // OP_RDSEED:

    // OP_VFMADDSUBPS:
    // OP_VFMADDSUBPD:
    // OP_VFMSUBADDPS:
    // OP_VFMSUBADDPD:
    // OP_VFMADDPS:
    // OP_VFMADDPD:
    // OP_VFMADDSS:
    // OP_VFMADDSD:
    // OP_VFMSUBPS:
    // OP_VFMSUBPD:
    // OP_VFMSUBSS:
    // OP_VFMSUBSD:
    // OP_VFNMADDPS:
    // OP_VFNMADDPD:
    // OP_VFNMADDSS:
    // OP_VFNMADDSD:
    // OP_VFNMSUBPS:
    // OP_VFNMSUBPD:
    // OP_VFNMSUBSS:
    // OP_VFNMSUBSD:

    // OP_VFRCZPS:
    // OP_VFRCZPD:
    // OP_VFRCZSS:
    // OP_VFRCZSD:
    // OP_VPCMOV:
    // OP_VPCOMB:
    // OP_VPCOMW:
    // OP_VPCOMD:
    // OP_VPCOMQ:
    // OP_VPCOMUB:
    // OP_VPCOMUW:
    // OP_VPCOMUD:
    // OP_VPCOMUQ:
    // OP_VPERMIL2PD:
    // OP_VPERMIL2PS:
    // OP_VPHADDBW:
    // OP_VPHADDBD:
    // OP_VPHADDBQ:
    // OP_VPHADDWD:
    // OP_VPHADDWQ:
    // OP_VPHADDDQ:
    // OP_VPHADDUBW:
    // OP_VPHADDUBD:
    // OP_VPHADDUBQ:
    // OP_VPHADDUWD:
    // OP_VPHADDUWQ:
    // OP_VPHADDUDQ:
    // OP_VPHSUBBW:
    // OP_VPHSUBWD:
    // OP_VPHSUBDQ:
    // OP_VPMACSSWW:
    // OP_VPMACSSWD:
    // OP_VPMACSSDQL:
    // OP_VPMACSSDD:
    // OP_VPMACSSDQH:
    // OP_VPMACSWW:
    // OP_VPMACSWD:
    // OP_VPMACSDQL:
    // OP_VPMACSDD:
    // OP_VPMACSDQH:
    // OP_VPMADCSSWD:
    // OP_VPMADCSWD:
    // OP_VPPERM:
    // OP_VPROTB:
    // OP_VPROTW:
    // OP_VPROTD:
    // OP_VPROTQ:
    // OP_VPSHLB:
    // OP_VPSHLW:
    // OP_VPSHLD:
    // OP_VPSHLQ:
    // OP_VPSHAB:
    // OP_VPSHAW:
    // OP_VPSHAD:
    // OP_VPSHAQ:

    // OP_BEXTR:
    // OP_BLCFILL:
    // OP_BLCI:
    // OP_BLCIC:
    // OP_BLCMSK:
    // OP_BLCS:
    // OP_BLSFILL:
    // OP_BLSIC:
    // OP_T1MSKC:
    // OP_TZMSK:

    // OP_LLWPCB:
    // OP_SLWPCB:
    // OP_LWPINS:
    // OP_LWPVAL:

    // OP_ANDN:
    // OP_BLSR:
    // OP_BLSMSK:
    // OP_BLSI:
    // OP_TZCNT:
    TB_INSTRUM_ID_TZCNT_DREG_2_SMEM_2,
    TB_INSTRUM_ID_TZCNT_DREG_4_SMEM_4,
    TB_INSTRUM_ID_TZCNT_DREG_8_SMEM_8,
    TB_INSTRUM_ID_TZCNT_DREG_2_SREG_2,
    TB_INSTRUM_ID_TZCNT_DREG_4_SREG_4,
    TB_INSTRUM_ID_TZCNT_DREG_8_SREG_8,

    // OP_BZHI:
    // OP_PEXT:
    TB_INSTRUM_ID_PEXT_DREG_4_SREG_4_SREG_4,
    TB_INSTRUM_ID_PEXT_DREG_8_SREG_8_SREG_8,
    TB_INSTRUM_ID_PEXT_DREG_4_SREG_4_SMEM_4,
    TB_INSTRUM_ID_PEXT_DREG_8_SREG_8_SMEM_8,

    // OP_PDEP:
    // OP_SARX:
    // OP_SHLX:
    // OP_SHRX:
    // OP_RORX:
    // OP_MULX:

    // OP_GETSEC:

    // OP_VMFUNC:
    // OP_INVPCID:

    // OP_XABORT:
    // OP_XBEGIN:
    // OP_XEND:
    // OP_XTEST:

    // OP_VPGATHERDD:
    // OP_VPGATHERDQ:
    // OP_VPGATHERQD:
    // OP_VPGATHERQQ:
    // OP_VGATHERDPS:
    // OP_VGATHERDPD:
    // OP_VGATHERQPS:
    // OP_VGATHERQPD:
    // OP_VBROADCASTI128:
    // OP_VINSERTI128:
    // OP_VEXTRACTI128:
    // OP_VPMASKMOVD:
    // OP_VPMASKMOVQ:
    // OP_VPERM2I128:
    // OP_VPERMD:
    // OP_VPERMPS:
    // OP_VPERMQ:
    // OP_VPERMPD:
    // OP_VPBLENDD:
    // OP_VPSLLVD:
    // OP_VPSLLVQ:
    // OP_VPSRAVD:
    // OP_VPSRLVD:
    // OP_VPSRLVQ:
    // OP_VPBROADCASTB:
    // OP_VPBROADCASTW:
    // OP_VPBROADCASTD:
    // OP_VPBROADCASTQ:

    // OP_XSAVEC32:
    // OP_XSAVEC64:

    // OP_ADOX:
    // OP_ADCX:

    // UNTAINT INSTRUCTION HANDLERS

    TB_INSTRUM_ID_UNTAINT_DREG_1,
    TB_INSTRUM_ID_UNTAINT_DREG_2,
    TB_INSTRUM_ID_UNTAINT_DREG_4,
    TB_INSTRUM_ID_UNTAINT_DREG_8,
    TB_INSTRUM_ID_UNTAINT_DREG_16,

    TB_INSTRUM_ID_UNTAINT_DMEM_1,
    TB_INSTRUM_ID_UNTAINT_DMEM_2,
    TB_INSTRUM_ID_UNTAINT_DMEM_4,
    TB_INSTRUM_ID_UNTAINT_DMEM_8,
    TB_INSTRUM_ID_UNTAINT_DMEM_16,

    TB_INSTRUM_ID_UNTAINT_FIRST_2_DREGS_1,
    TB_INSTRUM_ID_UNTAINT_FIRST_2_DREGS_2,
    TB_INSTRUM_ID_UNTAINT_FIRST_2_DREGS_4,
    TB_INSTRUM_ID_UNTAINT_FIRST_2_DREGS_8,

    TB_INSTRUM_ID_UNTAINT_FIRST_3_DREGS_1,
    TB_INSTRUM_ID_UNTAINT_FIRST_3_DREGS_2,
    TB_INSTRUM_ID_UNTAINT_FIRST_3_DREGS_4,
    TB_INSTRUM_ID_UNTAINT_FIRST_3_DREGS_8,

    TB_INSTRUM_ID_UNTAINT_FIRST_4_DREGS_1,
    TB_INSTRUM_ID_UNTAINT_FIRST_4_DREGS_2,
    TB_INSTRUM_ID_UNTAINT_FIRST_4_DREGS_4,
    TB_INSTRUM_ID_UNTAINT_FIRST_4_DREGS_8,

    TB_INSTRUM_ID_UNTAINT_DMEM_2ND_1,
    TB_INSTRUM_ID_UNTAINT_DMEM_2ND_2,
    TB_INSTRUM_ID_UNTAINT_DMEM_2ND_4,
    TB_INSTRUM_ID_UNTAINT_DMEM_2ND_8,

    TB_INSTRUM_ID_UNTAINT_DREG_1ST_SUB_3RD_4TH,

    /* Not an instruction! */
    TB_INSTRUM_ID_END,
};

typedef struct {

    IB_INSTRUM_OPT opt;
    void *execute_function;
    tb_cc_pre_propagate_func_t pre_prop_func;
    tb_cc_post_propagate_func_t post_prop_func;
    void *tb_ctx;
} tb_cc_instr_hndlr_info_t;

typedef struct {

    IB_INSTRUM_OPT opt;
    void *execute_function;
    void *pre_prop_func;
    void *post_prop_func;
    void *spill_info;
    void *tb_ctx;
} tb_raw_instr_hndlr_info_t;

typedef struct {

    tb_ih_spill_func_t init_instr_hndlrs;
    tb_ih_spill_func_t destroy_instr_hndlrs;

    // Instruction Handlers.
    tb_instr_hndlr_t instr_hndlrs[TB_INSTRUM_ID_END];

    // Info used by instruction handlers.
    union {
        // Info used by instruction handlers.
        tb_cc_instr_hndlr_info_t instrum_cc_infos[TB_INSTRUM_ID_END];
        tb_raw_instr_hndlr_info_t instrum_raw_infos[TB_INSTRUM_ID_END];
    } tb_instr_hndlr_info;

}tb_te_instr_hndlrs_t;


#endif /* TAINT_ENGINES_INSTR_HANDLERS_TB_INSTRUCTION_HANDLER_H_ */
